Add various UI user overrides
krypto5863/COM3D2.ShapekeyMaster pull request #6
Opened 2024-10-13 04:33 UTC by Kotone4869

Added following configs for user overrides on UI component styles
1. Font size
2. Shapekey slider size
3. Minimum UI height
4. Minimum UI width
5. Shapekey name textbox width
6. UI default position
7. Toggle to hide condition row

Configs are placed in new section "UI 2" to avoid breaking existing ShapeKeyMaster.cfg
Updated GUI elements to be compatible with font size changes
Added another page manager row at the bottom of the shapekey list for easier paging when shapekey length exceeds UI height

2024-10-13 16:08 UTC, krypto5863 requested changes
It needs a bit of work, but it's good.

2024-10-13 16:08 UTC, krypto5863 commented on ShapekeyMaster/GUI/UIUserOverrides.cs
This needs caching. IMGUI is run every frame, that means a new object is being created every single frame when these functions are called. You could try saving the result, otherwise this adds GC load.

2024-10-13 16:08 UTC, krypto5863 commented on ShapekeyMaster/GUI/UI.cs
> +					ShapeKeyMaster.SimpleMode_ShowMoreFuntions.Value = GUILayout.Toggle(ShapeKeyMaster.SimpleMode_ShowMoreFuntions.Value, ShapeKeyMaster.CurrentLanguage["showMoreFuntions"], UIUserOverrides.getToggl
Let's try to keep it clean.

```suggestion
					ShapeKeyMaster.SimpleMode_ShowMoreFunctions.Value = GUILayout.Toggle(ShapeKeyMaster.SimpleMode_ShowMoreFunctions.Value, ShapeKeyMaster.CurrentLanguage["showMoreFunctions"], UIUserOverrides.getToggleStyleOverride());
```

2024-10-13 16:08 UTC, krypto5863 commented on ShapekeyMaster/ShapeKeyMaster.cs
> +		internal static ConfigEntry<bool> SimpleMode_ShowMoreFuntions;
Match the changes.
```suggestion
		internal static ConfigEntry<bool> SimpleMode_ShowMoreFunctions;
```

2024-10-13 16:08 UTC, krypto5863 commented on ShapekeyMaster/GUI/UI.cs
Instead of adding get style calls individually, why not create a custom GUISkin and apply a general style, only adding get style calls for unique variations?

2024-10-14 02:12 UTC, Kotone4869 commented on ShapekeyMaster/GUI/UIUserOverrides.cs
Added a dictionary to store results.

2024-10-14 02:12 UTC, Kotone4869 commented on ShapekeyMaster/GUI/UI.cs
> +					ShapeKeyMaster.SimpleMode_ShowMoreFuntions.Value = GUILayout.Toggle(ShapeKeyMaster.SimpleMode_ShowMoreFuntions.Value, ShapeKeyMaster.CurrentLanguage["showMoreFuntions"], UIUserOverrides.getToggl
Typo fixed.

2024-10-14 02:12 UTC, Kotone4869 commented on ShapekeyMaster/ShapeKeyMaster.cs
> +		internal static ConfigEntry<bool> SimpleMode_ShowMoreFuntions;
Typo fixed.

2024-10-14 02:14 UTC, Kotone4869 commented on ShapekeyMaster/GUI/UI.cs
Are you able to provide an example on how to create a custom GUISkin in C#? I don't have unity installed so I'm just going by what I can find online.

2024-10-14 03:22 UTC, krypto5863 commented on ShapekeyMaster/GUI/UI.cs
Happy to https://github.com/krypto5863/Illusion.KineMod/blob/master/Core_KineMod/IMGUIResources/CustomGUIStyle/Styles.cs

Look at the constructor in particular.

This must be applied and then unapplied as follows otherwise other IMGUI menus will be afflicted:

https://github.com/krypto5863/Illusion.KineMod/blob/d79bed03a036652b8b0eec93b20a2f41ce0f811e/Core_KineMod/IMGUIResources/KineModWindow.cs#L31

2024-10-14 06:06 UTC, Kotone4869 commented on ShapekeyMaster/GUI/UI.cs
Thanks, I changed them to use custom skin.

2024-10-14 15:01 UTC, krypto5863 commented on ShapekeyMaster/GUI/UIUserOverrides.cs
You should just make a static constructor and define your styles and skin there, once and done, no need for a dictionary. Also, you need to account for the user changing the settings as your styles are now saved instead of remade every frame, they'll need to be remade or updated, or indicate a restart is required.

You can follow [the previously given example](https://github.com/krypto5863/Illusion.KineMod/blob/master/Core_KineMod/IMGUIResources/CustomGUIStyle/Styles.cs) to see an efficient style/skin creation flow.

2024-10-14 15:25 UTC, Kotone4869 commented on ShapekeyMaster/GUI/UIUserOverrides.cs
So I actually had the custom styles as static variables in one of my earlier builds and the person tested mentioned the settings in ConfigurationManager doesn't work, so I made the change to what's there currently to allow real time changes, since restarting the game for many can take a long time. Not being able to edit the font size and slider size through ConfigurationManager could also be seen as a bug (my tester thought it was a bug). My understanding is six look ups to a dictionary by key should be nearly negligible performance wise.

2024-10-14 15:54 UTC, krypto5863 commented on ShapekeyMaster/GUI/UIUserOverrides.cs
Typically that's why you subscribe to the config changed event and update your styles, reactive when needed. But the choice is yours, I don't see a huge difference. Let me know when you're done.

2024-10-14 16:04 UTC, Kotone4869 commented on ShapekeyMaster/GUI/UIUserOverrides.cs
I'm done with my changes.

2024-10-14 16:52 UTC, krypto5863 approved these changes
Alright, guess we're good.

2024-10-14 16:52 UTC, merged